// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFpNyfNvwS_F0jl20GmQzpAKzsQhLdCuw',
    appId: '1:1057237681668:web:3de3713b15c81ed1b6d751',
    messagingSenderId: '1057237681668',
    projectId: 'flutterapps-f42c8',
    authDomain: 'flutterapps-f42c8.firebaseapp.com',
    storageBucket: 'flutterapps-f42c8.appspot.com',
    measurementId: 'G-08ZCME4GH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5y25LWRH3fNq2U8Q9mIpJcg9IIQTTZ3k',
    appId: '1:1057237681668:android:9e5dee7e8d41ab9cb6d751',
    messagingSenderId: '1057237681668',
    projectId: 'flutterapps-f42c8',
    storageBucket: 'flutterapps-f42c8.appspot.com',
  );
}
